# Application
quarkus.application.name=vehicle-service

  # HTTP
quarkus.http.port=8082

  # DataSource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=carsharing
quarkus.datasource.password=carsharing
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/vehicledb

  # Hibernate
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

  # OpenAPI / Swagger
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true

  # JWT (validation only — vehicle-service doesn't sign tokens)
quarkus.smallrye-jwt.enabled=true
mp.jwt.verify.publickey.location=public.pem
mp.jwt.verify.issuer=car-sharing

  # Dev profile
%dev.quarkus.hibernate-orm.log.sql=true

  # Prod profile
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:5432/vehicledb
%prod.quarkus.hibernate-orm.log.sql=false