# Application
quarkus.application.name=booking-service

# HTTP
quarkus.http.port=8083

# DataSource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=carsharing
quarkus.datasource.password=carsharing
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/bookingdb

# Hibernate
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

# OpenAPI / Swagger
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true

# JWT (validation only)
quarkus.smallrye-jwt.enabled=true
mp.jwt.verify.publickey.location=public.pem
mp.jwt.verify.issuer=car-sharing

# REST clients (booking calls other services)
quarkus.rest-client.user-service.url=http://localhost:8081
quarkus.rest-client.vehicle-service.url=http://localhost:8082

# Dev profile
%dev.quarkus.hibernate-orm.log.sql=true

# Prod profile
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:5432/bookingdb
%prod.quarkus.rest-client.user-service.url=http://${USER_SERVICE_HOST:localhost}:8081
%prod.quarkus.rest-client.vehicle-service.url=http://${VEHICLE_SERVICE_HOST:localhost}:8082
%prod.quarkus.hibernate-orm.log.sql=false

# NATS connection
quarkus.messaging.nats.connection.servers=nats://localhost:4222

# Declare the stream here too (idempotent — first service up creates it)
quarkus.messaging.nats.streams.BOOKINGS.configuration.subjects=booking.*

# Outgoing channel
mp.messaging.outgoing.booking-created.connector=quarkus-jetstream
mp.messaging.outgoing.booking-created.stream=BOOKINGS
mp.messaging.outgoing.booking-created.subject=booking.created

mp.messaging.outgoing.booking-started.connector=quarkus-jetstream
mp.messaging.outgoing.booking-started.stream=BOOKINGS
mp.messaging.outgoing.booking-started.subject=booking.started

mp.messaging.outgoing.booking-ended.connector=quarkus-jetstream
mp.messaging.outgoing.booking-ended.stream=BOOKINGS
mp.messaging.outgoing.booking-ended.subject=booking.ended

mp.messaging.outgoing.booking-cancelled.connector=quarkus-jetstream
mp.messaging.outgoing.booking-cancelled.stream=BOOKINGS
mp.messaging.outgoing.booking-cancelled.subject=booking.cancelled